---
  - name: Ensure hostname set (if not ip)
    hostname: 
      name: "{{inventory_hostname}}"
    when: not inventory_hostname|trim is match('(\d{1,3}\.){3}\d{1,3}')

  - name: Set swappiness
    sysctl:
      name: vm.swappiness
      value: "1"
      sysctl_set: yes

  - name: vm.max_map_count
    sysctl:
      name: vm.max_map_count
      value: "1048575"
      sysctl_set: yes

  - name: Format disk
    filesystem:
      dev: /dev/nvme0n1
      fstype: xfs

  - name: Mount disk
    mount:
      path: /data
      src: /dev/nvme0n1
      opts: noatime
      fstype: xfs
      state: mounted

  - name: Create cassandra directory if not exist
    file:
      path: /data/cassandra
      state: directory
      mode: '0755'

  - name: check if cassandra dir is symlink
    stat: 
      path: /var/lib/cassandra
    register: cassandra_data

  - name: remove the cassandra folder (only if it is a folder)
    file: 
      path: /var/lib/cassandra
      state: absent
    when: cassandra_data.stat.isdir is defined and cassandra_data.stat.isdir

  - name: setup set the cassandra dir to /data
    file: 
      src: /data/cassandra
      dest: /var/lib/cassandra
      owner: root
      group: root
      state: link

  - name: Add cassandra repo
    yum_repository:
      name: cassandra
      description: Cassandra Yum Repo
      baseurl: https://downloads.apache.org/cassandra/redhat/311x/
      gpgcheck: yes
      gpgkey: https://downloads.apache.org/cassandra/KEYS   
      repo_gpgcheck: yes

  - name: Install cassandra
    yum:
      name:
        - cassandra-3.11.13-1
        - cassandra-tools-3.11.13-1

  - name: Make sure cassandra owns data dir
    file:
      path: /data/cassandra
      state: directory
      owner: cassandra
      group: cassandra

  - name: Set cassandra config
    template:
      src: files/cassandra.yaml
      dest: /etc/cassandra/conf/cassandra.yaml

  - name: Set cassandra-env
    template: 
      src: files/cassandra-env.sh
      dest: /etc/cassandra/conf/cassandra-env.sh

  - name: Set jvm.options
    template: 
      src: files/jvm.options
      dest: /etc/cassandra/conf/jvm.options
    
  - name: Enable cassandra on boot
    service: 
      name: cassandra
      enabled: yes
      daemon_reload: yes
